### ISSUE TITLE
New Item Entry Window Width

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#1]
The New Item Entry Window is not wide enough; either the window should be built 100px wider or the text next to the title entry block needs to be half-sized.  For example, Firearms next to the title entry skips down a line, pushing the window to be longer.

**Comment by gmmatt** [comment]
This is a janky little problem with all the different items that we have in the system. The is a need to make the item type clear in the sheet, but also to have consistent formatting across different item types. This does create some issues in some sheets that needs t be adjusted.

**Comment by gmmatt** [comment]
Resolved in 0.92.0
