### ISSUE TITLE
Item input

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#10]
Would it be possible to have a single item input/entry window which encompasses all possible statistics in the game?  I ask because I'm dealing with Cyberware, particularly two items I'm using as an example -though there are certainly more- where I have Trigon Body Plating and Trigon Slicers.  Both are considered implants, though the body plating is considered a Prosthetic and the slicers are Subdermal Weapons, but the body plating also providers armor and the slicers also provide a weapon.

Yeah, that about covers it.

My thinking is that the entries can be displayed in their proper categories, whether various types of Perks by reality or the different types of Cyberware while also displaying as weapons.  For example, the Trigon Slicers are a Subdermal Weapon, which is where they belong, but they also have Melee Weapon statistics so they would show up in both places when the damage bonus triggers the melee weapon value of the item.

Other examples would be the Rocket Ranger Battlesuit, Dragon Armor, and the Ion Gusoku Armor.  These have multiple abilities and need to show up in several places on the Character sheet.

I know this is, likely, for a time down the road; I'm just expressing how helpful it could be to have these trigger across multiple locations on the sheet.

Something else to add would be Armor Piercing, especially for Guns and Ammunition.

**Comment by gmmatt** [comment]
I am thinking it might eventually be possible to create some kind of super-item category of items that allows an item to serve several purposes at once. But this is going to have to be something that happens down the road.

**Comment by pemerson71** [comment]
Rock on... certainly something to think about, hehe.

**Comment by pemerson71** [comment]
Armor Piercing has been taken care of from my original issue, above.  I'm not certain a super-item category is necessary, but would it be possible to make a super-item builder, each section of the builder (armor, defenses, weapon categories, buffs, debuffs, etc.) would have a check-block that, if the section is used, the block is checked and the item is generated on submit.

Another idea, since you've put Enhancements into Items... what about having a drop-down for each Enhancement to select a type of Item the Enhancements is when it's programmed into the system, which could add a section to the appropriate item slot on the sheet.  For example...

**Dragon Armor** (Core 85) has the Dart Thrower, Dragon Breath, Dragon Claws, Dragon Scales, and Giant Strength...
Dart Thrower ~ _Missile Weapons_, damage 13, range 10/20/40, six ammo available per load, up to two reloads or six each in the armor

Dragon Breath ~ _Missile Weapons_, 10 meter range, small blast, basically a flame thrower, three ammo, each target suffers 16 fire damage

Dragon Claws ~ _Unarmed Combat_, Strength +3 damage, Armor Piercing 2

Dragon Scales ~ _Armor_, +10 vs Fire (rather than +4)

Giant Strength ~ _Buff_, +2 Strength for tests and damage, but Toughness remains unaffected

All of these can be done, now, but they were a pain in the butt to do when I built it, before any of the Sources were made available.  Don't know whether or not this helps, but I sure hope it does.

**Comment by Algor0113** [comment]
As much is dealt with it now, it's inconsequential- maybe disposable, but don't want to close yet.

**Comment by pemerson71** [comment]
I don't believe this is inconsequential in the least.  It would be best to have a single form that covers everything multiple forms do, now, and the information from the single form fills out multiple entries/items, as chosen by the creator of the item(s).  What is available, now, is an overly complex and repeating system that could be handled entirely in a single form.

**Comment by Algor0113** [comment]
I am terribly sorry but I cannot uphold ressources for this. I close it for now. Requests for things like that were more seldom. If something is missing on existing items, we should rather consider to change these.
