### ISSUE TITLE
Restore Active Defense Functionality

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#103]
It has been lost in a recent update: 

Uncaught (in promise) TypeError: test.diceroll.toMessage is not a function
    at systems/torgeternity…e/torgchecks.js:651

**Comment by Algor0113** [comment]
Isn't that solved? @gmmatt

**Comment by rwanoux** [comment]
i think it is solved ; this error doesn't appear anymore : closed
