### ISSUE TITLE
Drag/Droppable Macros for Skill Tests and Attack-Type Powers

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#105]
Like we have for weapon attacks only atm.

**Comment by Durak-Git** [comment]
Need to handle permission during macro creation ``permission : {default : 3]`` ?
to allow the use of the same skill/attribute/power's macro by different players
(at the moment a macro can only be used by the creator unless GM changes permissions)

**Comment by pemerson71** [comment]
We have to make sure the minimum permissions level is set at Player or Trusted Player, not higher than that, please?  Or, allow GMs to assign those minimum permissions, based on what they want to see in their own games.

**Comment by Durak-Git** [comment]
This issue could be half-closed (just have to wait for the attack-type powers by Matt)
It was relevant before Spatula modified the macro creation for skill/attribute.
He handled the permissions

**Comment by Algor0113** [comment]
It's included now for players, GMs must select the specific token. So therefor it's closed
