### ISSUE TITLE
Item Restrictions (like racial restrictions) and Other Axiom requirements than Tech

### ISSUE THREAD

**Issue by discgolferusa** [MetaMorphic-Digital/torgeternity#111]
I am trying to figure out how to make an item that say requires a spirit axiom of 18 to not cause a contradiction, work.  Maybe spirit and magic axiom information should be added to the base item template like tech is.   Then a roll can check those like we would against tech.  

If I'm just not seeing another way that this can be currently accomplished though, please just let me know,

**Comment by gmmatt** [comment]
This one is not completely clear to me, so I'm closing it, but I would encourage you to resubmit and maybe re-word this if you think it is important.
