### ISSUE TITLE
Add Up as an Effect

### ISSUE THREAD

**Issue by discgolferusa** [MetaMorphic-Digital/torgeternity#112]
Example is the Ejection Seat program on the Charity Cyberdeck.  It allows the user to have an UP roll status when testing for Defeat.   It would be nice to be able to assign dice statuses like UP and Bonus Dice as an effect.  Say a weapon that always does bonus dice damage so it is auto rolled with damage or automatically gives you UP on your dice roll.

**Comment by Algor0113** [comment]
As you can always click "up" on the chat card, this won't be necessary.
