### ISSUE TITLE
Need Disfavored Attribute for Skill Test

### ISSUE THREAD

**Issue by discgolferusa** [MetaMorphic-Digital/torgeternity#113]
Need to have an attribute like the isFav but for tests that are disfavored.

**Comment by Algor0113** [comment]
Should be solved with 2.4.0- close it?

**Comment by pemerson71** [comment]
Matt's still working on the update to the skill test system, so I think he wants to leave this open, for now.

**Comment by Algor0113** [comment]
Overhauled, disfavored is implemented, therefor closed.
