### ISSUE TITLE
Attributes Need IsFav

### ISSUE THREAD

**Issue by discgolferusa** [MetaMorphic-Digital/torgeternity#114]
There are implants in the cyberpapacy that give favored status to attriute tests (COMPTE'S TRILON TENDONS give favored to Strength).

**Comment by gmmatt** [comment]
Another good suggestion. Thanks!

**Comment by Algor0113** [comment]
Urgent Label due to ground mechanic

**Comment by Algor0113** [comment]
It's already implemented by Durak as explained here:

https://github.com/Durak-Git/torgeternity/wiki/NEED-VALIDATION-%E2%80%90-SK-Data-elements-after-3.0.1#for-all-attributes-you-can-set-favored-example
