### ISSUE TITLE
Need ability to adjust hand size for actor

### ISSUE THREAD

**Issue by discgolferusa** [MetaMorphic-Digital/torgeternity#115]
Need to be able to adjust the hand size of an actor with a specific item in their inventory.   Example is the Orrorsh Medal Carnifex Princeps.  Which increases the hand size by 1 at the start of a scene.

**Comment by rwanoux** [comment]
can't the player  just draw another card ? I don't think that cards limit have been implemented

**Comment by Algor0113** [comment]
@discgolferusa I can't see the point in this issue, please, can you give a detailed description what the matter on this is?

The hand size is note limited or counted anywhere. There is an automation for possibility regain on start of an act, but not for destiny cards/cosm cards. Would you please so kind and describe what should happen? Thank you :)
