### ISSUE TITLE
Item Restrictions (like racial restrictions) and Other Axiom requirements than Tech

### ISSUE THREAD

**Issue by discgolferusa** [MetaMorphic-Digital/torgeternity#118]
Some items have restrictions by race (dragon armor is for Dwarf only as an example) and other items have Spirit or Magic axiom restrictions.  Items that are holy, sacred, enchanted, arcane and artifact items. 

Holy items require Spirit axiom of 14
Sacred items require Spirit axiom of 18
Enchanted items require Magic axiom 13
Arcane items require Magic axiom of 23 
Artifacts require Magic axiom of 24

Use of these items in to low of an axiom will cause contradictions, just as in tech restrictions.

This doesn't even get into the quantity limits that a character can have for the given types as well, but if we can get these restrictions added and made to handle contradiction checks that would be a big step forward.

**Comment by Algor0113** [comment]
Closed as it is already in pipeline on #46
