### ISSUE TITLE
Strange issue trying to use system

### ISSUE THREAD

**Issue by williamkeller** [MetaMorphic-Digital/torgeternity#119]
Hi. I'm seeing something really odd when trying to start up a new world with Torg Eternity. I haven't seen anyone else report this problem, so I assume that it's just me.

I can install the system and create a world just fine. But when I try to create an actor, I get a sheet that only has the actor's name available ([screenshot](https://drive.google.com/file/d/1NTDkUQYHT1h6foJNICqkG9TB2Qwyl6Y_/view?usp=sharing)). Same issue trying to create a melee weapon ([screenshot](https://drive.google.com/file/d/1UDQ1Qdng4N7-2y8q8KD3e842y_WVjbIX/view?usp=sharing)).

I see a couple errors in the javascript console. They don't seem related to the actor sheet, but I didn't troubleshoot that line of thinking too far. ([screenshot](https://drive.google.com/file/d/17G_hyb4AjA8U3R5unv2bVp5EV0htwEDb/view?usp=sharing)).  

I'm using Foundry v9, build 255, and Torg Eternity 2.3.5, and Chrome 99.0.4844.51.

Other foundry systems work just fine (mostly DCC and Eclipse Phase).

**Comment by gmmatt** [comment]
Hey William - can you come find us on the #ulisses-torg channel of the Foundry Discord server? I can help you more there, but it looks like your host site is missing some system files.

**Comment by Algor0113** [comment]
Was this solved? Looks like a user based problem

**Comment by rwanoux** [comment]
I think it can be closed...
