### ISSUE TITLE
Targetting attack NPC with 0 skill

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#121]
When attacking an NPC physically who has 0 skill in dodge, melee and /or unarmed, the test can't be resolved.

**Comment by rwanoux** [comment]
I wasn't able to reproduce the bug, i set a npc with 0 in those skills but was able to make an advanced roll that performed well

**Comment by Algor0113** [comment]
In foundry discord torg channel from 03/29 User teotismus:

I'm not sure this is a bug, but the combat automation against threats does some funny stuff. When the targeted opponent doesn't have the relevant Defense skill (Dodge, etc.), the popout window's DN does not default to the attribute, but instead defaults to 0. This only seems to affect physical attacks, interaction attacks seem to work well. Has anyone else noticed this?

**Comment by rwanoux** [comment]
solved with the new npc computation
