### ISSUE TITLE
documentdata is not iterable

### ISSUE THREAD

**Issue by MSleipnir** [MetaMorphic-Digital/torgeternity#127]
All the threats I've created don't show any abilities and when I try to change them I get the message: "DocumentData is not iterable"
Foundry: v.269
modules: all deactivated
Torg: v 2.3.7

**Comment by gmmatt** [comment]
Hi there MSleipnir - not sure what is going on here, but could you come over to the Foundry Discord server and describe your problem in the #ulisses-torg channel? There are several of us in that community that can help with your problem.

**Comment by gmmatt** [comment]
Resolved in Torg 2.3.9
