### ISSUE TITLE
Size in Threats

### ISSUE THREAD

**Issue by Durak-Git** [MetaMorphic-Digital/torgeternity#129]
(Perhaps will be obsolete with Power DN management)
Some Threats have an initial sizeBonus set with 0 (value for Normal).(I don't have access to non-normal size threats for test)
If you change it in the sheet, it keeps the text  information, that is not well understood in line 304 of torgchecks.js
![image](https://user-images.githubusercontent.com/97435195/166162918-0cf58db7-82d1-41f1-bc3d-e5ef967b265a.png)
New threats have the text description defaulted to 'normal' (not 0)

**Comment by Durak-Git** [comment]
No pb with physical attack
(That's why I speak of Power DN Management)

**Comment by Algor0113** [comment]
Done already, therefor closed
