### ISSUE TITLE
Add Kinesis to Firearms List

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#13]
The Psionic Power Pyrokinesis is a ranged fire attack with 14 damage, but there's no classification for it under Firearms, so it can be rolled; please add the skill Kinesis to that list?  Thank you.

**Comment by gmmatt** [comment]
Paul- the system is designed so that the psionic power itself can be rolled. You set it up with Kinesis as a skill and than place the damage description in the damage field, and then you roll it from the Powers tab.

**Comment by pemerson71** [comment]
Yeah, things in the system have begun to run together for me, because I've been working on setting things up so much, so I missed that.  My apologies.  Thank you.
