### ISSUE TITLE
Changes/Options for Dice Rolls

### ISSUE THREAD

**Issue by SEforbinproject** [MetaMorphic-Digital/torgeternity#132]
We've actually built some custom css to display test results differently as we just could not wrap our heads around how they were currently being displayed; we found that the information order and how we interacted with  it was:

ACTION TOTAL
DN
Result Level

Skill Value
Bonus Number
Modifiers

Dice Roll

Possibly having a couple of options for how tests are displayed might be useful?

**Comment by rwanoux** [comment]
Could you share your custom css. Or maybe share an image of how you would like it look like.

**Comment by gmmatt** [comment]
SEforbin - 

If you're interested in digging into how the die results get generated and displayed, send me a DM on Discord and I'll be glad to describe the basics for you.

**Comment by gmmatt** [comment]
We do need to develop a more compact format for those messages eventually, or at least have an option for a more compact format.

**Comment by SEforbinproject** [comment]
Righto - bearing in mind I'm not the guy who put this together, it was one of my players who is a web developer. So we've implemented this using Firefox only by adding in this style sheet. (the section at the end covers the chat/die rolls)

[userContent.txt](https://github.com/gmmatt/torgeternity/files/8641994/userContent.txt)

**Comment by SEforbinproject** [comment]
![image](https://user-images.githubusercontent.com/69514528/167168906-43023da7-afcb-410f-9b33-f3b9ed72aa37.png)

That's what we have in the chat window, it misses the DN sadly but we've found it to be a more accessible way of reading the results

**Comment by SEforbinproject** [comment]
Similarly, the character sheet for players is less compact, but we've found it a little quicker ti use in play - YMMV.

![image](https://user-images.githubusercontent.com/69514528/167169300-c0b3614e-6d9b-4548-83e5-33713e34a4f1.png)

**Comment by gmmatt** [comment]
Just FYI - there is an easier way to do this than hacking Firefox. There is a module called Custom CSS (or something like that) that the GM can run in Foundry that should do the same thing for the GM and all players.

**Comment by pemerson71** [comment]
For the second card image, above, the one where Konstantinov rolled an 18, perhaps the Action Total and the Success Type could be separate lines?  In this case, the Action Total would actually be 21, which produced the Outstanding Success, but the number is missing.  The die roll and the Action Total, with all modifiers, are equally important.  What's not important is seeing the actual dice rolled at the top-left of the card displayed, or any card we presently have; at least, that's my opinion.

**Comment by Algor0113** [comment]
At the time being, we don't have the capacity to implement a selectable style. I'm sorry, but we cannot add this atm.
