### ISSUE TITLE
[Archetypes (fr)] Bad translation for "Chat à dent de sabre"

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#134]
It's a translation mistake in the BBE core rules. If BBE accepts corrections in the Foundry database, we should use "Fauve à dents de sabre".
In English, "cat"  is the general name for "félin" or "fauve". It's a beginner's translation mistake. A "big cat hunter" doesn't hunt Siamese or Main Coons cats, but lions and tigers. ;-)

**Comment by rwanoux** [comment]
Even if it is a mistake i have to stick to the french translation :(
