### ISSUE TITLE
[Archetypes (fr) translation] Names with an article

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#135]
It would be better to remove the article. It's very strange in the archetype list, et it's akward for alphabetical sorting, since it uses the article and not the real name of the archetype. It would also allow to uniformise names, and have everywhere a  upper-cases letter

L'élu edeinos => Élu edeinos
L'inventeuse excentrique => Inventeuse excentrique
La chasseuse primitive => Chasseresse primitive
La chercheuse de reliques => Chercheuse de reliques
La combattante de la Résistance => Combattante de la Résistance
La cybersorcière => Cybersorcière
La gardienne elfe => Gardienne elfe
Le chasseur de monstres => Chasseur de monstres
Le détective dur à cuire => Détective dur à cuire
Le flic que rien n'arrête => Flic que rien n'arrête (on plus, c'est une femme, l'article masculin était gênant)
Le guerrier Dragon => Guerrier dragon
Le justicier masqué => Justicier masqué
Le Prêtre renégat => Prêtre renégat
Le Récupérateur => Récupérateur
Le samouraï électrique => Samouraï électrique
Le Vagabond des royaumes => Vagabond des royaumes
loup blanc => Loup blanc

**Comment by rwanoux** [comment]
I will see with the french distributor what he prefere

**Comment by Algor0113** [comment]
@Dame-du-Lac 
As rwan resigned some months ago, I can't possibly know if this is solved or not. Is this still an issue?

**Comment by Dame-du-Lac** [comment]
Hi
I just checked. The issue is not resolved.

**Comment by Algor0113** [comment]
@Durak-Git say mate, do you have any contact to black book games to clear this?

**Comment by Algor0113** [comment]
As there are none informations whatsoever coming from black book, and the titles are RAW, I will close this without any changes.
