### ISSUE TITLE
[Actor/Threat sheet] Text untranslated

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#136]
In the Possibility (potential) entry, the text is untranslated. The translation should not have a capital letter in French, by the way.

<img width="697" alt="Capture d’écran 2022-05-13 à 09 59 15" src="https://user-images.githubusercontent.com/105451788/168238358-b9ad9a98-df33-4b37-86ea-886138995802.png">
.

**Comment by rwanoux** [comment]
it come from the french compendium from up the creek module / branch "french" ; the compendium has been fixed
