### ISSUE TITLE
[Items, Actor] 2nd and 3rd titles are not translated

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#137]
In the Effects tab, the titles "Passive Effects" and "Inactive Effects" are not translated, even with the translation existing in the .json lang files.

<img width="646" alt="Capture d’écran 2022-05-13 à 10 04 07" src="https://user-images.githubusercontent.com/105451788/168239161-fbcd7249-7d21-4eba-bc2f-4ca9c41b470a.png">

**Comment by rwanoux** [comment]
fixed
