### ISSUE TITLE
[Actor sheet, Threat] The default size of the window hide the "Close" option.

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#138]
Yoiu have to widen the window to make appear the button [X Close] on the sheet. It's not very convenient.

<img width="603" alt="Capture d’écran 2022-05-13 à 10 07 02" src="https://user-images.githubusercontent.com/105451788/168240123-c421888b-1cf0-4cec-8a67-da96171b05e4.png">
<img width="591" alt="Capture d’écran 2022-05-13 à 10 08 16" src="https://user-images.githubusercontent.com/105451788/168240136-f58d4251-c491-4f8a-a566-c1bed7fb216b.png">

**Comment by rwanoux** [comment]
the fact that the close button is hidden in your game comes from the modules you activated (babele and popout) that add the buttons "traduire" and "popout". 
we don't want to make the system compatible with all the modules but it's true that "popout" and "babele" are very widely used. I will fix this compatibility "exceptionally".

**Comment by rwanoux** [comment]
fixed in dev branch
