### ISSUE TITLE
[Actor/Menace sheet] A line break is missing between the name of the actor and the other caracs

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#139]
When the window is resized, if you expand it too much horizontally, the first line of caracs (Wounds, etc.) is just to the right of the Actor's name.
The nale should be alone on its line.

<img width="763" alt="Capture d’écran 2022-05-13 à 10 12 43" src="https://user-images.githubusercontent.com/105451788/168241050-fce6755f-ea53-4da0-acdd-a7b1f720d848.png">

**Comment by pemerson71** [comment]
This problem remains, even if one expands the sheet all the way from left-to-right, I find.  Of course, I'm not running at a super-sized resolution, but this is something where the Wounds, Shock, and Fatigue should probably be on the same line as Possibilities.  The Possibility Potential script could, then, be set below the Possibilities.

**Comment by Algor0113** [comment]
With new charsheet, this issue is now obsolete
