### ISSUE TITLE
[Actor/Menace sheet] Text after the Possibilities (potential) should not be in bold

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#140]
The text after the entry "Possibilities (potential)" should be in regular fobnt, not bold, to have a better readibility.

<img width="648" alt="Capture d’écran 2022-05-13 à 10 24 14" src="https://user-images.githubusercontent.com/105451788/168243025-8429806c-eff8-4840-a7fa-508bd3e51e72.png">

**Comment by pemerson71** [comment]
Honestly, I'm uncertain why that text is there, anyway.  What would be nice is if, when the Possibility Potential is entered, while constructing the threat-sheet Character, if there are no Possibilities to be had, that line at the top of the window would just not be there.

**Comment by Algor0113** [comment]
With the new charsheet, this issue is now obsolete
