### ISSUE TITLE
[Effects tables] Description of passives effects no translated

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#142]
There is no automatic translation for the title of passives effects, and the description of the passive effect.

<img width="615" alt="Capture d’écran 2022-05-13 à 10 40 32" src="https://user-images.githubusercontent.com/105451788/168245946-be64efc7-58b3-43ff-93ca-ff3eecb05d58.png">

**Comment by rwanoux** [comment]
fixed
