### ISSUE TITLE
Actor - Storm Knight] Bad section for the skill Armes de jet/Missile weapons. 

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#144]
The skill Armes de jet/Missile weapons is in the category "Other", it should be in the first category, "Combat".

<img width="451" alt="Capture d’écran 2022-05-13 à 15 04 05" src="https://user-images.githubusercontent.com/105451788/168289653-351a0281-a000-4007-9587-ef8dce6ecd00.png">
.

**Comment by rwanoux** [comment]
fixed in dev
