### ISSUE TITLE
[Actor - Storm Knight] Bad alphabetical order in skill list

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#145]
In the Combat skills' section , the order of the skills should be: Armes à énergie, Armes à feu, Armes de jet, Armes de mêlée, Armes lourdes, Combat à mains nues.
In the Other section, Équitation is at the end, and should be juste after Débrouillardise (an issue with the accented capitalu, perhaps?). Same thing for Débrouillardise, that should be above Discrétion…

<img width="364" alt="Capture d’écran 2022-05-13 à 15 08 24" src="https://user-images.githubusercontent.com/105451788/168290185-eb8789d2-0c21-4783-b525-ba97ea047c08.png">
)

**Comment by rwanoux** [comment]
Le trie alphabétique est fait de manière logiciel afin que l'ordre soit respecté pour chaque langue. Je regarderai comment gérer les accentuations.

**Comment by rwanoux** [comment]
fixed in the FR-compendium branch
