### ISSUE TITLE
[Actor] Summary of Perk is not transated in the Actor sheet summary

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#146]
When you open an Perk item, the category is indeed translated.
But when you double-click on the name inside the Actor sheet to get the summary, the category revert to the English version.

<img width="563" alt="Capture d’écran 2022-05-15 à 14 38 57" src="https://user-images.githubusercontent.com/105451788/168473412-8d1cdf7f-a691-4352-aabb-fc3d0b032cef.png">
<img width="745" alt="Capture d’écran 2022-05-15 à 14 39 13" src="https://user-images.githubusercontent.com/105451788/168473422-14f59ff2-8e97-4895-a95c-027a501452ed.png">

**Comment by rwanoux** [comment]
fixed in dev branch
