### ISSUE TITLE
[Defense and DN] Innacurate target values

### ISSUE THREAD

**Issue by Durak-Git** [MetaMorphic-Digital/torgeternity#148]
Attacks don't take values in Defenses Block for DN (with Shift-click or with macros)
They target the skill (physical or interaction)
![Attacks_dont_target_Defenses](https://user-images.githubusercontent.com/97435195/168479978-2641edc0-d595-4284-bafe-d37548bc0da0.png)

**Comment by Durak-Git** [comment]
This is in 2.4.1 beta in test

**Comment by Durak-Git** [comment]
Corrected in 2.4.0 beta 2
**except** with macro shortcuts

**Comment by Algor0113** [comment]
@Durak-Git are you fine to lift the macro shortcuts out of this ticket?

**Comment by Durak-Git** [comment]
Yes

**Comment by Algor0113** [comment]
Closed, macros will be lifted out as the defences are working correctly with patch 2.4.0
