### ISSUE TITLE
[Actor/Storm Knight] No way to add  Bite/Claw or Unharmed combat in the weapons section

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#150]
When you have a Edeinos character (for example), it's impossible to add the Bite/Claws to the list of weapons, because there is no way to add a special capacity to a Storm Knight sheet. If you try to cheat by adding it to the Melee weapons list, it associates it to the wrong skill (Melee Weapon instead or Unarmed Combat).
It's the same issue if you want to add the Unarmed Combat to an human, dwarf, elf, etc. list of weapons, to be able to use it during a fight (with the damage calculation, etc.).

**Comment by gmmatt** [comment]
Hi Dame. You should be able to do this by setting up an item called a "custom attack." Let us know if that works.

**Comment by Dame-du-Lac** [comment]
It works ! Thank you very much

**Comment by Algor0113** [comment]
Closed, solved.
