### ISSUE TITLE
Reality as PowerSkill

### ISSUE THREAD

**Issue by Durak-Git** [MetaMorphic-Digital/torgeternity#151]
To solve this problem
"the core earth spells of Torg Or Treat does not require a magic skill test but a reality test"
proposition to add Reality as required
![image](https://user-images.githubusercontent.com/97435195/169154835-23eade12-d537-4e0d-b006-b8c327ff6237.png)
![image](https://user-images.githubusercontent.com/97435195/169154888-8bb01851-d169-464d-a171-39776604067a.png)

**Comment by Algor0113** [comment]
Done in patch 2.4.0.
