### ISSUE TITLE
Type of actor not translated

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#157]
When you create a new actor, the two types presented are not translated.
It should be "chevalier des tempêtes" for "stormknight" and "menace" for "threat".
<img width="494" alt="Capture d’écran 2022-06-01 à 00 30 29" src="https://user-images.githubusercontent.com/105451788/171294918-2deb9204-7717-42d5-bbba-1c083e15908d.png">

**Comment by rwanoux** [comment]
fixed in dev
