### ISSUE TITLE
Not enough room to display a lot of Perks prequisites

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#158]
There is a lot of space on the left side of the Perk sheet. And often, one line is not enough to display all the prerequisites of a Perk.
Perhaps it's possible to add one or two lines for this entry, to have a better readibility?
<img width="174" alt="Capture d’écran 2022-06-01 à 10 55 09" src="https://user-images.githubusercontent.com/105451788/171367367-3e74c562-923f-4988-ac70-c75c0381a714.png">

**Comment by pemerson71** [comment]
I've found this to be a problem, as well.  Perhaps instead of a text entry, it could be increased to a text box?
