### ISSUE TITLE
Earned XP and Auto-populating Clearance Level

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#16]
Earned XP is not something a Player, or even a Trusted Player should be allowed to enter.  Rather, it should be the GM that tracks XP and enters it for their Players, and then the Clearance Level should Auto-populate off that.  A Player can modify their Unspent XP -though I'm not certain I like this happening, either, though I imagine it would be terribly difficult to set up an advancement scheme/page for them to record their improvements, and then the cost of those improvements is actually what lowers Unspent XP for them.

Just rambling, right now, because it's freakin' late, hehe.

**Comment by pemerson71** [comment]
Alright, covered this, but it was something that, again, came up in game-play...

I guess the only thing to add, here, is that if Clearance is not to be automated, it doesn’t always set like it’s supposed to.  Two of my Player's Characters and one of my NPCs had reset to Alpha clearance while I was away from the game.

**Comment by rwanoux** [comment]
i have added a new setting where GM can choose if players are able to modify XP
![gmview](https://user-images.githubusercontent.com/18176317/162561569-ff0b5c29-f129-40fc-a38a-95faf913eedd.png)
![playerview](https://user-images.githubusercontent.com/18176317/162561582-5276cefc-63ac-49dd-9cb0-ff1650b177cd.png)

**Comment by pemerson71** [comment]
BRILLIANT!  Thank you.

     ~Paul (Just Paul/Sir Alain Fisk)
