### ISSUE TITLE
[Perk Item] The Dropdown menu is not in alphabetical order

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#160]
Once translated, the dropdown menu listing all the perk's categories is not in the new language alphabetical order.
<img width="163" alt="Capture d’écran 2022-06-06 à 15 48 16" src="https://user-images.githubusercontent.com/105451788/172173934-c204cc4f-4ea9-4617-9bb0-4f1da3fcec34.png">

**Comment by pemerson71** [comment]
To add to this, few of the menu's, in any language, are in alphabetical order.

**Comment by BadIdeasBureau** [comment]
There's a feature suggestion for Foundry which is tracked in the "might make it into V10" milestone, which would solve this easily: https://github.com/foundryvtt/foundryvtt/issues/7237

If that makes it into v10, then we can do this in a v10 only version with very little effort. If it doesn't, we can roll our own helper to do this, but that's going to take a bit more work.

**Comment by BadIdeasBureau** [comment]
This is now in V10 dev 3, I'll poke at it as part of the v10 updates

**Comment by pemerson71** [comment]
You rock, BIB!!!  There's little that irks me more on this planet than lists that are out of order, hehe.  Yes, I am THAT MUCH of a nerd, and more, LOL.

**Comment by Algor0113** [comment]
Enhancement badge, could possibly alphabetic sorting all comboboxes.
