### ISSUE TITLE
[Suggestion] Identify core decks based on an item property, rather than name, and identify compendium via a localised string

### ISSUE THREAD

**Issue by BadIdeasBureau** [MetaMorphic-Digital/torgeternity#163]
Currently, the setUpCardPiles function identifies each deck in the compendium by name.  This causes issues for localisation, as a) if the user changes the name of e.g. the Drama Deck to be localised into their language, then this function will not realise that deck is already imported, and b) if a compendium of localised decks is provided, then the correct deck will not be imported.

Instead, I propose adding a new property to the Cards template for decks, e.g. `deck.data.data.usage` (coming up with a useful name that doesn't conflict with `type` but conveys the right meaning is hard, open to suggestions), and then refactoring setUpCardPiles to search for decks with the appropriate value for that property, e.g.

```
    index = await pack.getIndex({fields:data.usage})
    if (game.cards.find(deck => deck.data.data.usage === "drama") == null) {
        const itemId = pack.index.find(deck => deck.data.usage === "drama")._id;
        let deck = await game.cards.importFromCompendium(pack, itemId);
        deckSetting.dramaDeck = deck.name
    }
```

Potentially as part of a bigger refactor, since that could probably be made into a function that just took a string for the decktype (e.g. by matching the valid values for `usage` to the keys of `deckSetting`), making the setUpCardPiles function easier to maintain in future.

Additionally, by changing line 3 of setUpCardPiles.js to
`const pack = game.packs.get(game.i18n.localize("torgeternity.packs.coreCards"));`, a localization string could be provided to automatically select the correct decks for a given language on initialization.

I'm happy to work on this, I just want to make sure I'm not riding over anyone by doing this.

**Comment by gmmatt** [comment]
Thanks BadIdeasBureau!
