### ISSUE TITLE
[Suggestion] Provide a default "landing page" scene on initial world creation, to ensure that the scene controls are active

### ISSUE THREAD

**Issue by BadIdeasBureau** [MetaMorphic-Digital/torgeternity#164]
I love the scene control button with the Torg tools in it, but there's one significant UX problem - in a new world, with no scene active, all scene control buttons are disabled.

A quick and easy fix for this would be to provide a "landing page" scene with some kind of nice background, which is imported into a new world (e.g. if(game.scenes.size === 0) import), which would give the new GM a nice landing page to look at, and activate the scene control buttons.

Further improvements to this could include adding journal pins to the scene pointing to various setup guides, or other information there to improve new user experience.

**Comment by rwanoux** [comment]
Done in dev Branch
