### ISSUE TITLE
Defense values invisible if not changed

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#168]
Since the last update, all the defenses values are invisible if you don't have a modifier applied.
If there are modifiers, only them appears…
In the image example, the character is small so she have a +2 bonus on her physical defenses
<img width="752" alt="Capture d’écran 2022-06-21 à 18 26 35" src="https://user-images.githubusercontent.com/105451788/174850791-714f38a8-ee3e-4e6f-b784-8e25c732fc0d.png">
.

**Comment by rwanoux** [comment]
It has already been fixed, thanks. Have you update your system?

**Comment by Dame-du-Lac** [comment]
I updated the 13th June… Will do a new update
