### ISSUE TITLE
Fatigue Effect of armor not implemented

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#169]
Since the last update, the Fatigue value doesn't change, even if an item of the character has an passive effect that augment the fatigue

<img width="781" alt="Capture d’écran 2022-06-22 à 13 21 27" src="https://user-images.githubusercontent.com/105451788/175017406-a6631336-8813-455d-9eaa-77e1a6f469e9.png">
<img width="812" alt="Capture d’écran 2022-06-22 à 13 21 39" src="https://user-images.githubusercontent.com/105451788/175017500-84a9f52b-162a-4a8e-b00a-18cec72535c2.png">

**Comment by gmmatt** [comment]
Thank you for reporting this. This has been fixed and will be updated in the next release.

**Comment by Algor0113** [comment]
Fixed
