### ISSUE TITLE
Derived Values

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#17]
Likely these are already known about, but I thought I would address them, here, to insure their importance, based on what happened this last pay weekend, 23 Jan 2021...

Derived values to be completed: Move, Run, Toughness, and Armor.  Cosm Axioms.  Experience Points.  

These do not always set like they’re supposed to, like Evidence Analysis used to do.  For example, my Elf Character had his Toughness and Armor set, but when I went back in Saturday night, the Toughness had reset to 5, when my Strength is 9, and my Armor value was set to 0 when it should have been 1.

**Comment by gmmatt** [comment]
This should be fixed in 0.90.3, but I am going to leave this open a little longer in case the problem persists.

**Comment by pemerson71** [comment]
Did you mean 0.90.4?  I'm just asking because we're in 0.90.3 and those specific issues were not yet fixed.
