### ISSUE TITLE
Possibility Automatic Reduction and GM Awards

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#18]
I can't remember if I've brought any of these subjects, before, but I think they bear repeating based on the familiarization I was trying to do with my Players this past Saturday evening...

Are Possibilities supposed to automatically reduce when you click on the Possibility title in the Stats tab?  If so, how can a GM give out rewards which Players cannot mess with?  I'm thinking more of venues where everyone meeting to play are not necessarily friends, such as with Torganized Play and the like.

**Comment by pemerson71** [comment]
It's likely better this issue goes away.  Having played now for two-and-a-half years after writing this, originally, my personal feeling goes to ensuing Possibilities are decreased by hand, especially since Rwanoux built in the Possibility tracker for the GM... it's really pretty easy to ask the question, "Are you going to reduce your Possibilities or do you want me to?" than to have it go down.  It allows Players to wrestle with themselves whether or not they wish to spend a Possibility, rather than saying yes automatically and clicking the link for Possibility on either the Card or the Character Record.

I think you're likely to find that to be true for most play groups out there.

**Comment by Algor0113** [comment]
It's convenient, but massive convenient! Let us do that ASAP :)

**Comment by Algor0113** [comment]
Done in #286
