### ISSUE TITLE
[Perk category] Cursed category missing

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#183]
The "Cursed" category of perks (from the Orrorsh sourcebook) is missing in the list of perks category, in the drop-down menu of the Perks item sheet.

**Comment by Dame-du-Lac** [comment]
By the way, if you add the perk category "Cursed" (from Orrorsh), it would be the ideal moment to add the new Pan-Pacifica perks : Biotech, Power Suit, and to replace "Ki powers" by "Vitality".

**Comment by gmmatt** [comment]
Updated for 2.5.1. Thanks for pointing this out!
