### ISSUE TITLE
Add AP as an Effect on an item

### ISSUE THREAD

**Issue by discgolferusa** [MetaMorphic-Digital/torgeternity#184]
Ok so the scenario is you have multiple types of ammunition for the Bulletsmith's Slayer Gun.   To handle these I was thinking of adding each ammunition as an effect on the base gun that the user can activate when using that particular round.  

Example Adamant Rounds give a +4 AP.   Would like to add an effect that can be turned on and off that would modify the guns AP value.

Or another example is to be able to modify the weapons damage value with an effect.   So that shells like Electric, Explosive, etc can add their bonus value to the damage in certain scenarios or can override the damage value of the weapon temporarily.

**Comment by Algor0113** [comment]
Thank you for your issue :)

In cause of overdo the item's interfaces and the forward computing of effects, this will be worked on- but not now.
