### ISSUE TITLE
[French only] Fautes d'orthographe dans le nom des cartes Destin

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#186]
Quelques cartes ont une faute dans leur nom :
Adrenaline => Adrénaline (carte 3) (manque l'accent sur le premier "e")
Echec de l'adversaire => Échec de l'adversaire (cartes 27 et 28) (majuscule accentuée)
Seconde Chance => Seconde chance (cartes 30 à 32) (en français, majuscule uniquement au premier mot dans un titre)
Coup de Grâce => Coup de grâce (en français, cartes 41 à 43)
Nemesis => Némesis (carte 45)
Soutient => Soutien (cartes 52 à 55)
Transfer => Transfert (carte 58)
Poussé de Réalité => Poussée de réalité (carte 59)

**Comment by rwanoux** [comment]
Je crois avoir corrigé cela dans la branch dédié aux compendiums fr. Je verifierai

**Comment by rwanoux** [comment]
tout n'était pas corrigé ; c'est fait, merci
