### ISSUE TITLE
[Custum skill] Impossible to make a test

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#188]
Hi
When you create a custom skill with the dedicated template, it appears in the Perks tab (why not), but it has no dice icon and it's impossible to make a test with it. When you click on the skill name, nothing happens… Even if in the templade the number of adds, the skill and the related attribute value were filled.
<img width="837" alt="Capture d’écran 2022-07-13 à 09 24 37" src="https://user-images.githubusercontent.com/105451788/178676451-e908042b-f9cc-45ac-b8b0-c65719d5bf6b.png">
<img width="525" alt="Capture d’écran 2022-07-13 à 09 27 54" src="https://user-images.githubusercontent.com/105451788/178676518-86cae1da-e5fc-42b0-904f-8f410e9c66bf.png">

**Comment by gmmatt** [comment]
This has been fixed and will be included in the version 10 patch.
