### ISSUE TITLE
[FR mistranslation] Perk "timestaken" should be "nombre d'achats"

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#189]
"Timestaken" is in fact the "number of times the perk is taken". It has nothing to do with an amount of time spent on the perk. The correct translation should be "Nombre d'achats".
<img width="543" alt="Capture d’écran 2022-07-15 à 22 37 14" src="https://user-images.githubusercontent.com/105451788/179307193-7ba46ec9-2cf2-498c-a607-1f7884898bdc.png">

**Comment by rwanoux** [comment]
this is a huge misunderstanding. I will correct that translation

**Comment by rwanoux** [comment]
I the core rule book the verb "choisir" is used each time a perk can be taken multiple times (instead of "achat"). So i think i will use "nombre de fois choisi". What do you think ?

**Comment by Dame-du-Lac** [comment]
"Nombre de fois choisi" is a little awkward and long, but it's difficult to find something better. "Nombre de choix", perhaps ?

**Comment by rwanoux** [comment]
let's go for "nombre de choix" ; if an user have any better idea we could easily change that translation
