### ISSUE TITLE
Attack Base Hand-to-Hand Damage Zero

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#19]
Attack (Hand-to-Hand) Base Damage: Strength does not calculate, remains 0.  Here's a video showing what was happening while we were checking out damage...

https://youtu.be/dBQ9lsZ4ZCM

**Comment by gmmatt** [comment]
HTH attacks/damage should be working as a custom attack in 0.92.3 when it is released.
