### ISSUE TITLE
[Name of perks categories] Small spelling mistake in French and obsolete perk category name

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#190]

**Comment by Dame-du-Lac** [comment]
In French, the perk category "Dwarf" should in a singular form => "Nain" (not _nains_)

The Ki powers category doesn't exist anymore. In the new Pan-Pacifica book, it's renamed "Vitality" (Vitalité in French).

<img width="167" alt="Capture d’écran 2022-07-15 à 22 44 26" src="https://user-images.githubusercontent.com/105451788/179309103-4e6bfab5-bd89-4202-b8dc-c2a7ad9fe290.png">

**Comment by rwanoux** [comment]
ok for the singular "Nain"
For "vitalité/pouvoir du ki" I will keep the old and add the new name. So it will be "Pouvoir du Ki/Vitalité".  Since the Pan-Pacifica source book isn't yet translated, not all french users will get this change.
