### ISSUE TITLE
[Suggestion][Spell] Balance between the columns

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#196]
Hi
The spell sheet seems a little unbalanced. Two much size on the left for the attributs of the spell, not enough on the right for the description.
Is it possible to reduce the left column and augment the right one?

**Comment by rwanoux** [comment]
i will have to check some style layout next week ; i will look at it also. I agree that having a larger column for descriptions text descriptions will be better

**Comment by gmmatt** [comment]
Rwan - I can do this adjustment if you don't want to. Just let me know.

**Comment by rwanoux** [comment]
done in dev branch ; the proble came from the select for difficulty... some of the options are very long strings so it streched the first column. I put a max-width on it
