### ISSUE TITLE
[French][Spelling] Spelling mistakes in some translations and missing translations of the dnTypes

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#197]
Normale => Normal (It refers to the "niveau", masculine noun)
Maneuvre de la cible => Manœuvre de la cible
Foie de la cible => Foi de la cible
Kinésie de la cible Kinesis => supprimer le [Kinesis] à la fin

For the missing translations, see the screenshot

<img width="308" alt="Capture d’écran 2022-07-23 à 10 49 47" src="https://user-images.githubusercontent.com/105451788/180598177-4bff2d9f-2104-4c03-8076-d784f3c3b2a8.png">

**Comment by Dame-du-Lac** [comment]
Another thing : for Willpower, you cannot translate by "Willpower" only since they are two options: "willpower or Spirit" or "willpower or mind".

**Comment by rwanoux** [comment]
already fixed in new release. thx
