### ISSUE TITLE
[French Spelling] Mistakes in the name of some Destiny cards

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#198]
Some cards have a spelling or typographic mistake in their names…

Card 3 - Adrenaline => Adrénaline
Cards 27, 28 - Echec de l'adversaire => Échec de l'adversaire
Cards 30, 31, 32 - Seconde Chance => Seconde chance
Cards 40, 41, 42, 43 - Coup de Grâce => Coup de grâce
Cards 52, 53, 54, 55 - Soutient => Soutien
Card 58 - Transfer => Transfert
Card 59 - Poussé de Réalité => Poussée de réalité

<img width="522" alt="Capture d’écran 2022-07-29 à 16 47 54" src="https://user-images.githubusercontent.com/105451788/181787000-cb96a8b8-f5ff-400a-ad29-43e934e65e07.png">
<img width="524" alt="Capture d’écran 2022-07-29 à 16 49 23" src="https://user-images.githubusercontent.com/105451788/181787025-60d9f845-4b14-4229-a6ea-5e5caa06f2d4.png">
<img width="515" alt="Capture d’écran 2022-07-29 à 16 50 53" src="https://user-images.githubusercontent.com/105451788/181787035-6fc4d480-e6d0-413c-baa4-dce695ca5ff9.png">
<img width="553" alt="Capture d’écran 2022-07-29 à 16 53 18" src="https://user-images.githubusercontent.com/105451788/181787046-95a72948-2f10-4920-9f75-143f191c4d83.png">

**Comment by rwanoux** [comment]
sorry but it seems that those errors are already fixed... 
i have been looking in the dev branch and in the last release it seems ok. are thoses errors still there after an update ?

**Comment by rwanoux** [comment]
fixed in dev branch
