### ISSUE TITLE
Favored Check Boxes

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#2]
It will likely become necessary to put some manner of check box next to each skill and attribute, perhaps even for some powers, for Favored and, perhaps, Disfavored skills, so the Player can choose whether or not they want to make a secondary roll for the skill.  There is presently no way to mark skills as Favored and/or Disfavored, which will make it imminently difficult for Players to remember what their Characters have as Favored, whether due to equipment, perks, etc.

**Comment by gmmatt** [comment]
Modified this request slightly to indicate that unfavored option is also being requested.
