### ISSUE TITLE
Pulp Powers to the Powers Tab?

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#20]
Should Pulp Powers show up in the Powers tab?  It’s confusing to not have them in the Powers tab, since they’re Pulp Powers.  On top of that, the Powers which show up, there, and have damage, which also really do NOT fit in the Gear tab, could be rolled like Miracles, Spells, and Psionics.  It just also seems weird to me that the only thing that doesn't up in the Powers tab are the only thing listed as actual Powers in the title, hehe.

**Comment by rwanoux** [comment]
should we close this issue ? the pulp powers are now under the "perks" tab

**Comment by pemerson71** [comment]
Perhaps this should be tested in the game and commented on, first.  I understand how the costs of perks and what-not works, but I still feel like, since they're powers, not just abilities, like normal Perks, should be in the Powers tab, along with Spells, Miracles, and Psionics.  It makes more sense to place an elevated ability, which is a power and not a perk, since perks are just special abilities that are not powered, cannot reach out like powers can, do not do anything more than bonuses or special, un-powered changes, in the Powers tab.

**Comment by pemerson71** [comment]
Having played a Pulp Hero in a couple of games, now, it's likely just as easy to have them in the Perks tab as the Powers tab, except for the problem of potential clutter on one page as compared to another, as Players continue to buy up Perks.

I'm not sure how to handle this one, except this one could probably be closed and, if others come up with the problem themselves, perhaps look at it, again?
