### ISSUE TITLE
V10: Spacing is too wide between special abilities in v10-compatibility branch

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#205]
On threat sheets, the spacing between each Special Ability (in collapsed/stat block mode) is too wide.

**Comment by Algor0113** [comment]
System puts an additional \<p>\</p> under the \<li> object (see screenshot). Not a css thing unfortunatly :( 
![2022-08-15 06_16_12-DevTools - localhost_30001_game](https://user-images.githubusercontent.com/80172941/184576479-c12db3c2-3159-436a-925b-937449cdfa60.jpg)

**Comment by rwanoux** [comment]
fixed in v10 compatibility branch
