### ISSUE TITLE
V10: System CSS interfering with visibility of input in modules

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#207]
The form input {} css on line 564 is interfering with the inputs in at least one module by causing a white-on-white input box. Could it be narrowed to apply only to our system dialogs?

(Tested on Mythic GM Emulator module, but pretty sure it will happen in other modules with white input backgrounds)

**Comment by Algor0113** [comment]
@gmmatt I need more information on this because I don't have these problems. Can I have a screenshot please and a direction where the buttons might be located?

**Comment by gmmatt** [comment]
Closing for now - doesn't seem to be a widespread issue.
