### ISSUE TITLE
Party Sheet Modification

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#211]
This past Sunday evening -and this has just occurred to me, now, because of a discussion going on in bug reports- I opened the Storm Knight Party Sheet from the Player list at the bottom left of the canvas.  Right now, my party list is showing ten Storm Knights worth of information, and there's no one in the game but me.  There should be NOTHING showing on that sheet.

Would it be possible to change the sheet to reflect only the Storm Knights a GM wants to see on there at any given time, please?  I have two Knights on there I MAY never see, again, but that's in the air, right now.  I have my own Aysle NPC who is not in the game, right now, and I have two more that are scheduled to return, but I don't know exactly when... COVID-19 has taken a toll on finances and jobs and they're in the midst of recovery.  The two I may never see, again, are Nephews and their Mom has been an absolute twit long enough that it's finally caught up with them.

The only five Storm Knights I have in my Possibility Wars folder are the ones that have been playing in this adventure.  The Storm Knights I have in my friend's game -Stormy Knights- are full SKs but they do not show up on the Party Sheet because their Players, most likely, are hooked into their Possibility Wars Knights, instead.

I don't use the Party Sheet all that often, though I know it would make my life easier if I would use it; that's a bad habit I have that I am trying to change.  However, when using the Party Sheet, to have it show only the Knights whose Players are logged into the game or, more helpful than that, only the Knights I choose to show on the Party Sheet -for when I'm trying to plan the next phase of a game, for example- would be absolutely amazing.  I suppose that's a ton of work, isn't it?

Thank you for anything you can put toward this.

**Comment by Algor0113** [comment]
Done with #286
