### ISSUE TITLE
V10: Links to journals are not working in item description

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#214]
In 5e it's working fine :(

**Comment by Algor0113** [comment]
Main link architecture:

@UUID[Compendium.te001-core-rulebook.rules.pwneQ55M0nnDH0Us.JournalEntryPage.EhKa65cpHvodUl2L#explosives-and-area-effect-attacks]{Explosives & Area Effect Attacks}

@UUID[
Compendium
.te001-core-rulebook.rules
.pwneQ55M0nnDH0Us
.JournalEntryPage
.EhKa65cpHvodUl2L
#explosives-and-area-effect-attacks]
{Explosives & Area Effect Attacks}

**Comment by gmmatt** [comment]
Resolved in version 2.6.4
