### ISSUE TITLE
V10: No esc context menu when torg menu is selected

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#218]
If you hit esc to reach logout or other point during have selected the torg menu in left control bar, the menu isn't shown up but produces an error:
![unknown](https://user-images.githubusercontent.com/80172941/189510573-6ba5cbb0-9b13-47da-910f-d7bb5883b8a0.png)

**Comment by gmmatt** [comment]
This appears to have been resolved in a previous update, without being marked as resolved here. When you hit escape from the Torg menu, it now closes the menu without generating a bug. Hitting it a second time brings up the esc context menu. This is the same behavior as with all other windows.
