### ISSUE TITLE
Built-in Card System

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#22]
Why we need a built-in card system.  Matt, you should see a BUNCH of issues in the accompanying video.  Players need to be able to have some control over cards, such as being able to trade cards and take cards.  The following video, much longer than the others, demonstrates what's going on...

https://youtu.be/GxhSheZllZk

**Comment by gmmatt** [comment]
Edited this to show built-in card system as requested feature.

**Comment by gmmatt** [comment]
Done and done.
