### ISSUE TITLE
V10: Chat Display bubble in items are broken

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#221]
After clicking the chat bubble, foundry creates an error, and the item is not displayed. Error messages see attached screenshots
![2022-09-12 06_35_08-#bug-reports _ Torg Game System - Discord](https://user-images.githubusercontent.com/80172941/189574818-0b4ace69-564e-490c-bc55-10df75c5f61f.jpg)

**Comment by gmmatt** [comment]
Resolved in 2.6.5
