### ISSUE TITLE
Lots of 'dead' space & padding in Journal pages

### ISSUE THREAD

**Issue by SEforbinproject** [MetaMorphic-Digital/torgeternity#224]
Compared to other implementations I run on Foundry, the Torg system's implementation for editing Journal pages seems to have a lot of dead space, leading to a 'keyhole surgery' experience. Would it be possible to release some more of that space? I've attached some images to show what I mean.

![Slide1](https://user-images.githubusercontent.com/69514528/190625019-2b8a4de6-79c2-4cbf-bdd3-be260907f65b.JPG)
![Slide2](https://user-images.githubusercontent.com/69514528/190625040-56dd1e29-ffd1-4c5d-a113-588633762260.JPG)

**Comment by SEforbinproject** [comment]
Also, for the drop-downs, it's white text on a beige background - it's quite eye-strain-y to read, something simpler and starker would probably make it easier on the eyes.

**Comment by Algor0113** [comment]
Solved with push 83af6832163eee7cd5669eabc97a3de602bddb22 in dev branch

**Comment by Algor0113** [comment]
Forgot to do something about the dropdowns 🤣

**Comment by Algor0113** [comment]
Backgrounded some boxes in upload 1206af8d6690d4982ed03d295e219322d6a7d1d3
