### ISSUE TITLE
Card preview from chat window small and unreadable

### ISSUE THREAD

**Issue by SEforbinproject** [MetaMorphic-Digital/torgeternity#227]
When hovering over a card icon in the chat window (such as when it's been played) the preview is tiny and unreadable (see image). This was tested on a vanilla install that only has Torg modules in place (tested on Firefox & chrome).

![Card Small](https://user-images.githubusercontent.com/69514528/193053091-9ddd6765-79fa-4ff9-b9a4-f702bba7fbb4.png)

**Comment by gmmatt** [comment]
This appears to have been resolved in a previous update, but we did not mark it as resolved.
