### ISSUE TITLE
[Suggestion] Threat actor sheet, "notes" access

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#229]
It would be great if it were possible to have an easy access to the "notes" tab when the sheet is not developped. This tab contains the description of the creature, and being able to get it without having to do all the "developping process" would be invaluable.
Perhaps a clickable button or a tab somewhere, when the sheet is in compact form ?

**Comment by Algor0113** [comment]
Thinking about a chatcard output of the notes by a rightclick context menu entry
