### ISSUE TITLE
Player Feedback

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#23]
Good morning.  Since opening up some playtesting opportunities, I've received the following feedback from Mike Zaret at Torganized Play on Facebook...

1) All attributes should begin with a base of 8... "On the initial stat values. I agree that characters should be able to fill in their own, but 40pts is the base for a storm knight. Right now it looks like 25, that is why I suggested 8, since 40/5 = 8. Not looking for a generation tool, but base totals should be correct on stats and possibilities." ~ I attempted to explain that it wasn't on our priorities list, but I would pass it on, as Players should be filling in all of that information.

2) Space for skill bonuses... On attributes and skills there should be a space for placing temporary/permanent bonuses for Perks and various Power and Card additions.

3) The request has been put out to split the skills into the various sections like the basic Torg Eternity Character sheet. ~ The only reasoning I can think of to do this is because of familiarity through the original sheet and sheets that have been rebuilt.  Whenever I look at, or build for myself, Character sheets that split in skills is ALWAYS prevalent and, frankly, I feel as though it makes game-play easier to deal with, overall.  Besides, doing this could also allow for an expanded skills section for languages, professions, and scholarly pursuits.

**Comment by gmmatt** [comment]
I have broken these three enhancement requests down into separate issues. Closing this issue, but all three component issues remain for consideration.
