### ISSUE TITLE
[Threat sheet] A way to identify defensive only skills

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#230]
Hello
Some defense skills have score between parenthesis in the rulebooks, because they are meant for defense purpose only, and cannot be used for offensive interactions. But the threat sheet doesn't accept parenthesis, only numerical values (it's logical, if you want to make a skill roll with this value).
Is there a way to make a small "something" to check to indicative "defense only" in the input part of the sheet, that put a icon after; or parenthesis, around the skill value in the summary above?
Or perhaps to have a list of "defense only values" somewhere on the threat sheet ?

**Comment by Algor0113** [comment]
New threat sheet is there, therefor closed.
