### ISSUE TITLE
Spanish Compendium/Compendium Choice

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#233]
Based on our discussion, this issue concerns being able to make a choice for primary Compendium and Card use, whether that is the user marking Compendiums you wish to have hidden or selecting a primary Compendium for use, where all others are to be hidden.

This has become a problem for Spanish users and I wouldn't be surprised it will need to be expanded in the future.

The solutions discussed were...

"What if we had THREE checkboxes instead of one: (1) Hide official EN compendiums, (2) Hide official DE compendiums, and (3) Hide official FR compendiums? That way, if - say - an ES speaker wants to use the EN compendiums while running the system with ES localization, they can do that?"

"Why not just have "Hide Official Compendiums: EN ( ) DE ( ) FR ( )""

"Ummm, what about, instead... "Use Compendium: (dropdown for EN, DE, and FR)".  This could hide all the other Compendiums, not take up too much space and, perhaps, just be set into the Configuration rules, then?"

**Comment by gmmatt** [comment]
I like the drop-down, but maybe also include "None" and "All" as options.

**Comment by Algor0113** [comment]
For the time being, there were no other complaints as spanish and english foundry do display EN automatically. Closed for now.
