### ISSUE TITLE
Custom Skills on Skill List Without Favored Column

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#234]
![image](https://user-images.githubusercontent.com/72530664/200361249-1561082d-110c-404b-bbd3-76b2d6a2b491.png)

Adding Languages to a Friend's Knight sheet, this morning, I found the problem seen in the image, above.  With no Favored column added, all of the columns are off a bit.

Is it possible to select a Favored status in the Item sheet when developing the new skill, as well?

**Comment by gmmatt** [comment]
Alignment issue is corrected in the next release. Will add a feature request to give Favored status to custom skills.
