### ISSUE TITLE
Bonus Die Infinite Roll is, Indeed, Finite...

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#238]
Good evening, again.

Typically, a Bonus Die will roll only once or twice to help add damage to a target; however, tonight during play I, as the GamesMaster, rolled one BD for damage.  The first lazy 8 came up, the die face switched to 5 and rolled the next die, which came up with the same infinity symbol, the die face switched to 5 and rolled the next die, which stopped with the infinity symbol.  The roll went no further.

Now, I've NEVER had a BD go so far, before -the bad guy was, obviously, squished-, but I'm wondering if something's stopping the die from turning even further?

**Comment by Durak-Git** [comment]
![image](https://user-images.githubusercontent.com/97435195/202298638-10c58cd2-1fbf-4c13-a07a-49058dae3dfa.png)
The d6 formula is the same as this one with d2
I managed to go up to 7
It could be a Foundry bug, or dices showing to fast.
If you still have the chatMessage, can you check (clicking on the total) what is the sequenced values ?)

**Comment by pemerson71** [comment]
Yeah, I'm going to have to spend some time getting into this video to show you, for certain.  You know what, what you suggest might just be easier... let me see if I can find it...

Nope... I'll have to see if I can find it in the video.  I'm already trying to put out Possibility War Episodes 63-65 today and/or tomorrow, so let me see when I can get time.

**Comment by gmmatt** [comment]
I will close this for now, but if someone can replicate the issue we will reopen it later.
