### ISSUE TITLE
dexterity limitation with armor

### ISSUE THREAD

**Issue by rwanoux** [MetaMorphic-Digital/torgeternity#240]
it seems that the dexterity limitation doesn't work

**Comment by Durak-Git** [comment]
The effects works on this Character called "Twenty in all attributes"
![image](https://user-images.githubusercontent.com/97435195/204518143-8fe6f7eb-9cd9-491e-9900-f78e30648042.png)
It's not applied for skills (see Trick)
Archetypes armors don't have this effect set in fact.
![image](https://user-images.githubusercontent.com/97435195/204518968-bd2129c8-72c7-44d4-9db2-09c410207974.png)
