### ISSUE TITLE
[Suggestion] Integrate temporarily a bonus or penalty to an Attribute score

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#242]
Hi.
It will be great it would be possible to have the possibility to add temporarily a bonus or penalty to an Attribute, without having to use an effect. A lot of spells, miracles, special capacities can modify an Attribut, and it will be easer to be able to add or remove a number in a reserved box next to the attribute (see screenshot for an example). Once the number is entered, all the scores depending on that attribute will be automatically modified.
<img width="758" alt="Capture d’écran 2022-12-06 à 21 48 29" src="https://user-images.githubusercontent.com/105451788/206021455-0d49cc45-caf6-400f-bd19-988c43fd3ccc.png">

**Comment by Algor0113** [comment]
Sorry, won't do that. You can add a temporary bonus on the roll dialog. If it should be a more semi-permanent bonus, do it via an active effect.
