### ISSUE TITLE
Threat Defences not being recognised when tageted

### ISSUE THREAD

**Issue by SEforbinproject** [MetaMorphic-Digital/torgeternity#243]
When targeting a threat and resolving an attack it looks like the threat's defence values aren't being picked up. I've tested this in a vanilla install of Foundry with no modules. In the example below the Cyberwitch targeted the Edeinos and made a Fire Combat attack with their Godmeeter.

this is on v10, build 291 running Torg Eternity 2.8.0

![image](https://user-images.githubusercontent.com/69514528/207869357-f711d578-c5bc-4b6a-95b5-a52f8706f3ea.png)

**Comment by gmmatt** [comment]
Resolved in 2.8.1.
