### ISSUE TITLE
Combat Tracker Crashes When Participant Exits Combat

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#245]
(Reported by Pascal on Discord)
Hi, i think there is a bug in combat tracker actually. If one character choose to change his combat state at his token like this :
[1:04 AM]

[1:04 AM]
there is an error in debud console :
[1:04 AM]

[1:05 AM]
And if we click on the new turn button the list in combat tracker become unstable and some character disapear of the list
[1:06 AM]
i think that it's because when you're looping into the fighter list there is no check if a fighter is null or not in /Data/systems/torgeternity/module/dramaticScene/torgeternityCombat.js (edited)
[1:06 AM]
for (let i = 0; i < combatantLength; i++) {
                let c = x.contents[i]

                await c.setFlag("world", "turnTaken", false)
                let y = 0
            }
[1:07 AM]
you should probably make something like
[1:07 AM]
if( c == null) continue; (edited)

Pascal — Today at 1:32 AM
juste after "let c = x.content[i]"

**Comment by gmmatt** [comment]
Not able to reproduce this issue, but will keep it in the list for now pending more feedback from the user who reported it.

**Comment by Algor0113** [comment]
Couldn't reproduce neither on many attempts with various conditions. As 9 Month has passed and nothing is added, closed.
