### ISSUE TITLE
Add Unarmed Combat Damage Bonus Derived Attribute

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#249]

**Comment by gmmatt** [comment]
This is implemented in torgeternity actor in the upcoming threats update branch (and will eventually be released). It is also applied to the new threat sheet. It still needs to be applied in the new actor sheet.

**Comment by Algor0113** [comment]
I have no idea what that is about 🤣

**Comment by Algor0113** [comment]
Done in #286
