### ISSUE TITLE
[Enhancement] Better control of Possibilities

### ISSUE THREAD

**Issue by SwordofSpirit** [MetaMorphic-Digital/torgeternity#251]
The only ways I can see to adjust the number of Possibilities a character has is either manually changing the number on the sheet, or the GM using the buttons in the players list.

A few enhancements that would be great would be:

1) Some sort of button a player could press to spend a Possibility non-contextually (and update their current Possibilities)
2) Clicking to spend a Possibility on a chat card could update the character's current Possibilities
3) Some way of keeping track of which Possibilities are from specific cosms
4) Bonus: A button a player could press to spend a Possibility and show Soak results in the chat, for when they want to try to soak damage

**Comment by gmmatt** [comment]
Thanks for the suggestions! I have tagged this post as a potential enhancement for future reference.

**Comment by Algor0113** [comment]
Done in next release, cosm-specific possiblities will be a thing for later (and will be followed here: #287
