### ISSUE TITLE
Divide Skills into Sections

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#26]
The request has been put out to split the skills into the various sections like the basic Torg Eternity Character sheet. ~ The only reasoning I can think of to do this is because of familiarity through the original sheet and sheets that have been rebuilt. Whenever I look at, or build for myself, Character sheets that split in skills is ALWAYS prevalent and, frankly, I feel as though it makes game-play easier to deal with, overall. Besides, doing this could also allow for an expanded skills section for languages, professions, and scholarly pursuits.

**Comment by Algor0113** [comment]
I guess this can be closed- already done.

**Comment by rwanoux** [comment]
Let's close it.
