### ISSUE TITLE
zip file for v3.1.1 contains torgeternity.lock

### ISSUE THREAD

**Issue by farling42** [MetaMorphic-Digital/torgeternity#282]
The zip file which everybody downloads for version 3.1.1 has the LOCK file present, therefore the automatic update will not occur for any players until they manually unlock the game system.

**Comment by Algor0113** [comment]
Thank you for noticing. I'll see to it ASAP

**Comment by Algor0113** [comment]
With release 3.1.2 the lock file is not (and hopefully never ever will be) included.
