### ISSUE TITLE
Pulp Powers, Individual Focus or Perk?  And... enhancements.

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#3]
Spells, Psionics, and Miracles each have their own categories, obviously for spells, in the Powers tab.  Each of those begins as an individual Perk for purposes of allowing the selection and placement of spells, psionics, and miracles each in their power category.

In the realm of Pulp Powers, however, there is already an argument to be made, using Rays as an example, for those to be weapon items, because they project and do damage and are rolled to produce a hit and, in most cases, damage.  I believe the same is true for placing Pulp Powers in the Powers tab, NOT in the Perks tab, unless a name and a basic description is placed, there, and then particulars fed in the Powers tab.

That being explained leads me to a question about Enhancements for various Pulp Powers... I can see them being mentioned in up to three tabs: Gear, Perks, and Powers.  Listing them in Gear would be for Pulp Powers that require die rolls and can have Enhancements added to them.  Listing them in Perks is obvious, as they're supposed to be a Perk and, thus, the majority of the description should be placed there, though references to Gear and Powers tabs would be listed as necessary.  (NOTE: See the game I just invited you all to in order to see and understand what I'm talking about).  Finally, listing them in Powers is for any non-weapon properties that still may require a die roll and where Enhancements can be entered by hand to improve a Pulp Power.

Before any of you say I'm pushing too far, making things entirely too complicated, think both about the game we're playing -the crunch factor is less than RPPW, but still remains in Eternity- and the GamesMasters who run the game -who typically add or subtract from the rules, to customize the game for themselves- and you'll have your answer to my level of complexity, there. :)

My thought, here, is that Enhancements for anything in the game, including Pulp Powers, should be rolled into the Perks those Enhancements belong to, not separated as on the Perks tab.  If a box could be made for editing/entering Enhancements on a per-Pulp Power basis, that would be best, in my opinion.

**Comment by gmmatt** [comment]
This is similar suggestion to the super-item enhancement. I'll close this since it duplicates much of what was in the other one.
