### ISSUE TITLE
Missile Weapons is in the wrong skill category

### ISSUE THREAD

**Issue by Dame-du-Lac** [MetaMorphic-Digital/torgeternity#305]
The "Missile Weapons" skills appears in the "Other" skill category. It should be in the "Combat" category, and should appear even if it has no add.
<img width="376" alt="Capture d’écran 2023-11-28 à 01 32 15" src="https://github.com/gmmatt/torgeternity/assets/105451788/5090d739-71e1-49d2-8f2b-17ebee642a7e">

**Comment by Algor0113** [comment]
Interesting, as in the templates it is ordered to combat. We'll have a look ASAP before the next release.

Note to self: template.json line 218 property groupName is combat, so why is it not ordered into combat?
