### ISSUE TITLE
Issues from Discord

### ISSUE THREAD

**Issue by Durak-Git** [MetaMorphic-Digital/torgeternity#309]
> 2) Characters (it may just be threats) were being set to Unconscious when they reached their Shock total, instead of when they exceeded it as the rules state.
> 3) Being Vulnerable was incorrectly giving bonuses to Soak tests (this also may just be for Threats).
> 4) I can't get weapons on vehicles to work. I've set the skill value on the weapon, but when I click the little die icon to roll the attack, nothing happens. No pop-up, nada.
> 5) Also, Vehicle Defense is not being altered by the Maneuverability rating as the rules indicate.
I'm enjoying the system, btw 🙂  Just noticing these quirks as our games go along

2. will check, but I think I missed the 'greater'
3. Testing
4. It search for isFav, not present in the vehicle weapon, I will find a way
5. For this, I need rules Expert (and I will search anyway)

**Comment by Durak-Git** [comment]
There was a 1)
Skill moving in sheet during update
Very strange, but very true :) I caught it

**Comment by Algor0113** [comment]
To do:
- [x] Vehicle Defense

**Comment by Algor0113** [comment]
Closed with merge #310
