### ISSUE TITLE
Rework Chatcards

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#322]
KISS!
- [x] Make a \<details> tag for hiding details, avoiding TMI at once
  - [x] Change summary on foldout: Show / hide
  - ~~[ ] Insert option into settings so each player can decide if he wants to have it collapsed by default or not~~
    - Postponed to refactoring and part of #326 
- [x] Make clickables real \<button>s
  - Maybe just do borders around the things?
- [x] If *Possible disconnect* is shown, add the number
- [x] Success text color green, failure red, botch violet
- [x] Apply Damage & Soak damage buttons only with combat rolls
- [x] CSS Chatcard-Head out of a table into a grid!
- [ ] If +3 is clicked, the newly generated Chatcard has old header habits. Why?
  - Anyhow the complete cascade that worked before now doesn't work anymore. The class (.torgeternity-actor-icon) is still there, but doesn't get their styles from the torgeternity.css stylesheet, instead, getting the styles from vanilla - foundry style.css

**Comment by Gustl80** [comment]
Would be a really great addition.

**Comment by Algor0113** [comment]
I've not made buttons on roll altering elements, just borders and a slight background colour.
