### ISSUE TITLE
Ability to Select Skills Displayed on a Skill-By-Skill Basis

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#34]

**Comment by pemerson71** [comment]
This one I'm truly curious about... I'm just sad it's been 19 days since I checked in, here, last, hehe.  So, what do you mean by selecting skills displayed on a skill-by-skill basis?  I may be able to help with this.

**Comment by pemerson71** [comment]
Matt do you remember what this one was about?

**Comment by pemerson71** [comment]
I think, personally, the skills are in a really good place, right now and, since I still don't understand what you mean by "selecting skills displayed on a skill-by-skill basis", and it's been two-and-a-half years since you opened this, perhaps this one could be closed?

**Comment by Algor0113** [comment]
Closed, seems to be the same as #89 , if not, sadly, noone seems to remember what was this about :)

I'd be flattered if this is re-opened with a nearer description :)
