### ISSUE TITLE
Macros!

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#351]
Big one:
- [x] Introduce a macro hub on torg controls

Doing things to marked token:
- [x] Dealing fatigue
- [x] Revive from shock
  - [x] Completely
  - [x] partly- entering a number
- [x] Lift all status effects (stymied/vulnerable)
- [x] Reconnection
- [x] A macro to boost/debuff an attribute, defenses, it asks for value and duration, and apply effect (first window below)
- [x] A macro to show next drama cards (3 if I remember) to a player (I don't manage to change order at this moment)
- [x] So many times, a player says "I missclicked, not the card I wanted to play", so a macro that get the last played card to his owner' hand 

Doing things mainly:
- [x] Rolling BDs

**Comment by klenkes74** [comment]
Will the macros take care of removing the status effects according to the rules (after the next turn of the effected character) automatically? That would be awesome!

**Comment by Algor0113** [comment]
> Will the macros take care of removing the status effects according to the rules (after the next turn of the effected character) automatically? That would be awesome!

Nope, sorry, that is totally not possible. However, Durak works on a solution in the system itself. But as torg is torg, there are so much _buts_, that it's not that trivial.

The macros for removing status effects is for selected tokens on the canvas.

All in all I summarize, it is not excluded that these are a basis for code and possibilities, that will move into the system on one day in some way.

**Comment by Gustl80** [comment]
Have an idea for 3 macros that work similar:
Show all players a note/Journal entry with these information:
1. End of Combat - "Reduce destiny cards to 4."
2. End of Scene - "Fill destiny handcards to 4, then ..."
3. End of Act - "Throw away cosm card and draw a new one. Set possibilities back to 3 ..."
- Would be phrased the same way as in the rulebook

Goal: The GM only press 1 button and all players get the reminder what they have to do at this of the session point.

**Comment by Algor0113** [comment]
On end of combat, it would be absolutely possible to send out an reminder as soon as the gm clicks on 'end of combat'.

End of act, we already have a kind-of handler by resetting the possibilities, maybe we can emerge an automated card handling there?

The end of a scene is a bit more tricky as we don't have an actual trigger. Maybe really a macro or a button on the left torg menu. 

What do you think?

**Comment by Algor0113** [comment]
@klenkes74 I have good news, in v12.2.0 active effects like stymied etc. will be handled by clicking the "Done" Button (if you're the player of that character) or for threats, if you tick the checkmark in the combat tracker as gm in the combat tracker, if they do have a duration (what they indeed have if they're applied through the chat card output) :)
