### ISSUE TITLE
Install System Version

### ISSUE THREAD

**Issue by Durak-Git** [MetaMorphic-Digital/torgeternity#363]
When searching for TORG, sytem install, it proposes 3.0.1 version
It needs an update after this install to get the last version

![image](https://github.com/gmmatt/torgeternity/assets/97435195/88e9ebb7-6a6f-46b0-a386-a83db4dc051e)

**Comment by Algor0113** [comment]
Does anybody know what's happening here? If I remember correctly, that must have been around the time I took over. 

@gmmatt sorry to bother you, but do you have an idea what's happening? Did I skipped a step on the release procedure?

**Comment by Algor0113** [comment]
I have written foundry to get access / permission for releasing. So, this is pending.
