### ISSUE TITLE
Bug on item picture change/active effects staying

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#365]
As described [here](https://discord.com/channels/170995199584108546/842809090316828693/1219430197313409195)

- [x] correct picture assignment- let it stay if it isn't on creation
- [x] delete an ae if the apropriate item is deleted

**Comment by Algor0113** [comment]
If a item is deleted, the AE isn't. Need to change that

**Comment by Durak-Git** [comment]
> If a item is deleted, the AE isn't. Need to change that

It works, except for some Archetypes, where active effects do not have the perfect behavior
Toggling an "equipped" armor toggles the effect, but deleting the armor, do not delete the effect.

For picture, **giving an item to a character = create an item for this character**, so picture was set to default, I have a fix
