### ISSUE TITLE
system.other.possibilities.possMod

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#385]
Due to AE changes in Possibilities (e.g. perk _Prodigy_), Possibilities are overwritten by these AEs. We need a new datafield, something like \*points to title\*

**Comment by Durak-Git** [comment]
You want a ``system.other.possibiliies.initialPerAct``, something that can be _aeffected_ . And used with a macro/button, when starting a new Act, to set possibilities.
It needs the macro/button, and the dataModel change, possible then.

( 😊 I would reset everything to 3 (as the system permits at this moment, button could be adapted in fact), and let the player applies his perk bonus, let them work)

**Comment by Algor0113** [comment]
Let us bin that for the moment. Maybe we'll look into other handlings with reality AEs later.
