### ISSUE TITLE
Re-ordering gear, weapons, armor, Perks, Spells, Miracles, Psioncs, and Pulp Powers

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#4]
As small as many of the lines of gear, etc., are on the sheet, it can be exceedingly difficult to re-order the way a Player may want their list of _whatever_ on the sheet.  This goes for everything listed in the title of this post.

**Comment by pemerson71** [comment]
Just an update from this past weekend (1/25/2021)...

Dragging Perks, Gear, or Powers into place, to allow a Player to have them in the order they want, such as having old, less useful, or one-time effect Perks, Miracles, Spells, and Psionics toward the bottom of the list, and then allowing them to stack 'upwards' on the sheet to the more important and useful ones at the top.  Right now, it's really difficult to do and they don't always remain in the order the Player puts them in.  Would it be possible to have them ordered by use of arrows on the left or right side?

**Comment by gmmatt** [comment]
In testing this yesterday, it appears it is now possible to re-order lists of gear, powers, etc.

**Comment by pemerson71** [comment]
Matt,

     Here's the original write-up...

     Dragging Perks, Gear, or Powers into place, to allow a Player to have them in the order they want, such as having old, less useful, or one-time effect Perks, Miracles, Spells, and Psionics toward the bottom of the list, and then allowing them to stack 'upwards' on the sheet to the more important and useful ones at the top. Right now, it's really difficult to do and they don't always remain in the order the Player puts them in. Would it be possible to have them ordered by use of arrows on the left or right side?

     What I was aiming for was a way to, perhaps, classify them in an order... yes, you can drag things around into place, but they do not stay where you want them to be.  It's always a craps shoot because one can NEVER be sure when the way they reorder things is going to remain the way they desire, or not.  More often than not, if you log in and out enough, your stuff is NOT going to be in the order you want it in.  At the earlier Clearance levels in Torg, this is not likely to be that big a deal, but as you add things to your Character, they become increasingly difficult to manage.

     Is there anything that can be done about that?

     ~Paul
