### ISSUE TITLE
isNan is not defined

### ISSUE THREAD

**Issue by farling42** [MetaMorphic-Digital/torgeternity#402]
The migration code tries to call `isNan` but the correct spelling is `isNaN`

![image](https://github.com/gmmatt/torgeternity/assets/17485384/0791cebc-a80d-4d8e-a635-b9c246ba6818)

common.js:115:9 is `torgeternity/module/data/actor/common.js`  (in new code added in Torg 3.8.1)

New bug in 3.8.1

**Comment by Algor0113** [comment]
Thank you for reporting
