### ISSUE TITLE
Damage Rolls - Trademark Weapon Perk

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#42]
Modify damage rolls so that they account for trademark weapons, which re-roll on an initial result of 1.

**Comment by pemerson71** [comment]
Would it be possible to make this an automatic re-roll.

**Comment by pemerson71** [comment]
Is the juice worth the squeeze?

**Comment by Algor0113** [comment]
Would need some hardcoding, or at least an own method. I'd say, as you aptly mentioned above @pemerson71, I don't want to close it without a result, but it's not a lot juice, ergo it's inconsequential

**Comment by Algor0113** [comment]
connects to #250
