### ISSUE TITLE
[Feature Request] Toggle for the chat card additional information expansion

### ISSUE THREAD

**Issue by SwordofSpirit** [MetaMorphic-Digital/torgeternity#420]
It would be great if there were a setting to have the chat card info expanded by default. Alternatively (or in addition) putting the damage value in the always displayed section would help a lot. We regularly have situations where for one reason or another we have to fiddle with something after it goes through the automation, and need to see the damage vs. toughness numbers.

**Comment by Algor0113** [comment]
I'll introduce a new option in the settings to let the details always be shown clientwise- so, if someone doesn't want it, (s)he mustn't
