### ISSUE TITLE
Delaying Possibility expenditure until Soak dialogue box is complete

### ISSUE THREAD

**Issue by SwordofSpirit** [MetaMorphic-Digital/torgeternity#421]
Sometimes I open up the Soak box, and end up closing it before continuing for one reason or another. The current behavior is that it subracts the Possibility as soon as you click on Soak, but it would be more useful if it waited until you click Roll in the dialogue to subtract the Possibility, so additional Possibilities aren't accidentally spent.

**Comment by Algor0113** [comment]
Not quite a bug, not quite an enhancement, but don't wanna make a new label

**Comment by Algor0113** [comment]
Agreed on that, the possibility expenditure should be after the dialogue is through
