### ISSUE TITLE
Party Sheet

### ISSUE THREAD

**Issue by Durak-Git** [MetaMorphic-Digital/torgeternity#433]
The party sheet shows some unwanted SK's attributes
![image](https://github.com/user-attachments/assets/08a17316-fc71-424e-9f9d-c8032c37dfe1)

**Comment by Algor0113** [comment]
And that's the problem:

![Screenshot_20240722_151232_GitHub.jpg](https://github.com/user-attachments/assets/898aca21-1325-4bea-9ebd-05787906ce1e)

Will avoid that through handlebar checks
