### ISSUE TITLE
Active Effect for Favored Skill doesn't work

### ISSUE THREAD

**Issue by Gustl80** [MetaMorphic-Digital/torgeternity#439]
It seems that the Active effect that toggles Favored for skills on doesn't do what it should.
Tested on the Archetype Edeinos Wanderer from LL with Persuation and Der abtrünnige Priester from System with Computer.

**Comment by Durak-Git** [comment]
Manage to do the job on my side,
Is the effects  like this ?
![image](https://github.com/user-attachments/assets/ab4de7b9-acc9-4a2b-b8d7-90796f32722c)

**Comment by Durak-Git** [comment]
![image](https://github.com/user-attachments/assets/17a5e696-ed72-4aa8-b830-6730ea05732f)

**Comment by Durak-Git** [comment]
Hum, sorry, computer has an error it seems,
Searching ....

**Comment by Algor0113** [comment]
The Parameter should be 1 and not true. Odd. Haven't thought that I've changed the type of the field. Did I?

If so, we'll need a migration

**Comment by Gustl80** [comment]
Here I opened the English Priest that have True entered at the AEs. Doesn't work:
![Screenshot 2024-07-30 151956](https://github.com/user-attachments/assets/88f65fc5-6a53-4001-b523-17504037326d)

The German version still have 1 in it but doesn't work either
![Screenshot 2024-07-30 151957](https://github.com/user-attachments/assets/43c63c62-760c-4c1a-89eb-52344b73b030)

@Durak-Git are you using the DEV branch of the system, as I use that version and the released one seems to have the same problem?

**Comment by Durak-Git** [comment]
not``True`` but ``true``, all lowercase

**Comment by Durak-Git** [comment]
> The Parameter should be 1 and not true. Odd. Haven't thought that I've changed the type of the field. Did I?
> 
> If so, we'll need a migration

``isFav`` is enforced boolean type. Before 0 was equivalent to false, and 1 to true. Not anymore
![image](https://github.com/user-attachments/assets/24d1a4bd-d551-472a-b13a-c2d764a8f7fd)

**Comment by Gustl80** [comment]
> not`True` but `true`, all lowercase

That did the trick. I need a migration that update all the AEs in the items to change "True" or "1" into "true". Can't update that by hand.
