### ISSUE TITLE
Additional Modifiers to Core Mechanics Rolls

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#45]
Add other modifiers to core mechanics rolls such as:
* Aiming (+4 to Fire Combat/Missle Weapons/Heavy Weapons attack)
* Concentrating (-2 to willpower, spirit, magic, psionics, faith).

**Comment by Sarsmund** [comment]
And what about a generic modifier White you can put your number?
I am timing about combined actions in particular, where the number is variable

**Comment by gmmatt** [comment]
Resolved with enhanced tests update

**Comment by Sarsmund** [comment]
> Resolved with enhanced tests update

Super!
