### ISSUE TITLE
Secondary axioms for items

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#46]
Some items have a secondary (non-tech) axiom. Add fields to store these axioms on item sheet.

**Comment by Algor0113** [comment]
See also closed issue #118

**Comment by pemerson71** [comment]
I know the way I add my items is something like...
(Tech 19) .45 Caliber Pistol
(Magic 15) _Magic Spell or Item_
(Social 09) _Psionic Ability_

If you want these to be able to show up in order, single digit items need a 0 in front of the other number.

**Comment by pemerson71** [comment]
Would this be used as a stepping stone to an automated Surge or Disconnect system?

**Comment by Algor0113** [comment]
Urgent as a base mechanic.
