### ISSUE TITLE
Automated Value-calculation for all items with prices.

### ISSUE THREAD

**Issue by Gustl80** [MetaMorphic-Digital/torgeternity#486]
As the Value of the price is calculated by a formula this could be filled automatically and would erase the double work and potential errors when you fill out items.

This would be needed for the following item types:
- Armor
- Firearm
- Gear
- Heavy Weapon
- Implant
- Melee Weapon
- Missile Weapon
- Shield
- Vehicle

**Comment by Algor0113** [comment]
Data model prepareDerivedData() in general.js?

**Comment by Gustl80** [comment]
No idea but the vehicle actor already used that for speed and price. Maybe you can look up how it is managed there.
