### ISSUE TITLE
Unskilled Rolls

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#5]
I haven't tested all of the skills, but I know I cannot enter a number into the Adds column for Evidence Analysis and have it stick.

Also, not-unskilled normal skills (no adds in them) would only be 1d20x10 , because they only roll again on 10s, with no minimums.

Finally, not-unskilled bold skills (no adds in them) cannot be rolled at all.  Those skills are Air Vehicles, Alteration, Apportation, Conjuration, Divination, Kinesis, Language, Lockpicking, Medicine, Precognition, Reality, and Telepathy.

Is there a way to write checks for these, and then roll them as appropriate?

**Comment by gmmatt** [comment]
The Evidence Analysis issue is fixed pre 0.9.0. Saving this one as a feature request for unskilled rolls.

**Comment by gmmatt** [comment]
Should be fixed in 0.90.6
