### ISSUE TITLE
Adding other races/races as items

### ISSUE THREAD

**Issue by rwanoux** [MetaMorphic-Digital/torgeternity#52]
- [x] Dialog for 'you really wanna delete this?'
- [x] Delete race-related perks on race deletation
- [x] Prevent to add more than 1 race item
- [x] Add perks to race item
  - [x] DataModel
  - [x] drop Handler
  - [x] Get it onto the sheet
  - [x] Delete handler
- [x] Possibility to add race related perks that will be added to the actor as soon as the race item is droped
  - [x] _onDrop() method
- [x] Add attributeMaximum to actor document's attributes
  - [x] NO! Data handling!
- [x] On attribute change, check if base > attributeMaximum (BEWARE of perks like _Super Attribute_, check for AE!!!)
  - [x] General increase
  - [x] AE .maximum handling
- [x] Show max attr on sheet in edit mode
- [x] Data for Custom Attacks (like Perks)
- [x] Cluster racial perks on an other section on the actor sheet
- [x] Add Custom Attacks on the perks section
- [x] Migration on existing actors
- [x] Compute hardcoded section / Maybe do other config possibilities instead of hardcode

**Comment by gmmatt** [comment]
We definitely need this. It is a fairly common request.

**Comment by gmmatt** [comment]
One possibility is to make Races an item, which then allows effects that enforce racial maximums. Per Veronerus.

**Comment by pemerson71** [comment]
Ooh, I like that idea... races as items, instead of selecting one from the drop-down?

**Comment by Algor0113** [comment]
See also #62 

Highly approving the "Race as an item" idea, as it's common in other systems (like 5e)

**Comment by Gustl80** [comment]
MaxAttribute needs to be modifiable because of Perks like Super-Attribute.
