### ISSUE TITLE
Shock does not update with strength

### ISSUE THREAD

**Issue by 8thavenger** [MetaMorphic-Digital/torgeternity#55]
On Storm Knight Sheet, updating characters strength does not update shock value

**Comment by gmmatt** [comment]
Thanks for submitting the issue. However, under the rules, Shock is based on Spirit, not Strength (CRB, p. 70). The sheet does appear to update property for Spirit.

If I am missing something here, please let me know!

**Comment by 8thavenger** [comment]
My bad, toughness is based on strength, shock on spirit.   
  

  

  

  
  
  
  
  
>
