### ISSUE TITLE
Improved system for calculating damages.

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#57]

**Comment by Sarsmund** [comment]
Yes, please. This is one of the major missing feature comparing to Roll20

**Comment by gmmatt** [comment]
Added in most recent version

**Comment by Sarsmund** [comment]
Thank you!
Could you help me to make it work?
What exactly should I do?
When I target the token and roll for the attack, no calculations for wounds
and shock seem applied to the target token.

Il Dom 7 Nov 2021, 20:32 gmmatt ***@***.***> ha scritto:

**Comment by gmmatt** [comment]
Hi Sarsmund.

The system will not deduct the wounds and shock from the target token, but it will tell you how many wounds and shock should be deducted in the chat output. You will need to manually adjust the wounds and shock on the token.

**Comment by Sarsmund** [comment]
Ok, thanks.
Is there a way to automatically reduce anno after firing?
