### ISSUE TITLE
Provide a way to roll Multi Actions

### ISSUE THREAD

**Issue by BadIdeasBureau** [MetaMorphic-Digital/torgeternity#66]
Multi Actions are a wonderful part of the Torg system, but are also the kind of slightly complicated and fiddly thing that are great to automate via a VTT. It would be excellent to have some handling for those in system.

Easy suggestion:  Provide an obvious button on the character sheet which can be used to just roll a dice and generate a bonus, for multi-action turns.

Harder Suggestion:

During initiative, shift+clicking on a rollable thing in character sheet pops out a "multi action window".  

Shift clicking on more things adds them to the list in that window (perhaps with some checks for whether the same skill is being used twice, or two spells are being cast, etc), and allows a separate modifier to be set for each one (e.g. for cover, drama card effects, multi-targeting).

A button at the bottom of the application will roll a Multi-Action - roll a d20, calculate bonus, apply multi-action penalty and any modifiers, and then show the result for each action.  Cards can then be applied to each final result, possibilities/up/etc can then be applied to the bonus roll.

I appreciate this is going to be a fairly chunky thing, but the "push your luck" aspect of Multi Actions are one of the great things about Torg as a tabletop system, and handling them nicely in the Foundry system would be excellent.

**Comment by gmmatt** [comment]
I 100% agree with the idea that the system needs a way to handle multi-actions and I've actually put a lot of thought into how to get this done. It also needs to handle modifiers to skill rolls. At the same time, I want it to be easy to do "quick" skill and combat checks as well, without having to navigate through complex dialog boxes. I am thinking something along the lines of click for the simple check (the current system) and shift-click for the more detailed roll. Or, possibly, using the chat dialog to add to a roll.

**Comment by gmmatt** [comment]
Addressed this (somewhat) in enhanced roll update.
