### ISSUE TITLE
GM Possibility Pool

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#68]
Starting at Beta level, GMs get a pool of possibilities. Need to have a way for the GM and players to know how many possibilities the GM has at any given time.

**Comment by rwanoux** [comment]
As a flag on the Gm user, displayed the same way as characters possibilities? Does it need special buttons? For which actions?

**Comment by gmmatt** [comment]
I am not sure about how to implement it. Is there a way to set up a persistent environmental variable? And maybe have a small box where it displays somewhere in the UI?

**Comment by rwanoux** [comment]
Flags are persistent. For exemple cosms for scenes are flags. And it is totally possible to add a custom form app in the ui. Not a big deal now that I know how to manage it. If you can draw a sketch it could show me the needs.

**Comment by gmmatt** [comment]
In that case, I would say to use a flag and to just display possibilities for the GM the same way they are displayed for players in the player list. I don't know that we need a separate UI element now that I think about it.

**Comment by gmmatt** [comment]
Added some time back by Rwan!
