### ISSUE TITLE
Races

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#7]
Please add Edeinos to the list of available races in the Stats tab?

Also, will there be a way for GMs to add new races to the stats tab as their games progress?

Suggestion: Make it so a Character's race can be dragged over from Items, please?  That way, GMs will have the basic races when they download the system, but will not be limited to those races, giving them the ability to create more.

**Comment by gmmatt** [comment]
Added in v 0.9.0
