### ISSUE TITLE
Add attack-type powers to main SK page

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#72]

**Comment by Sarsmund** [comment]
Yes please!!

**Comment by pemerson71** [comment]
This would work, I think, if the SK Sheet was re-designed to be Landscape on the screen rather than Portrait by orientation with the canvas.  I believe it will cluster a Portrait-style SK Sheet, though.

**Comment by Algor0113** [comment]
Already implemented, therefor closed.
