### ISSUE TITLE
Creating Special Abilities

### ISSUE THREAD

**Issue by fscx7** [MetaMorphic-Digital/torgeternity#74]
So when I create a Special Ability for Threats when I enter its text and saving it the box shows blank.  This happens when I created it as a stand alone item and as an ability on the threat sheet.  On the threat sheet all I see is the Ability with no text like  Armor: slimy flesh +1  for a Gospog of the 2nd planting for the Living Lands.

Here are a few images of what I see.
1st one with texted added in edit window and saved.
![image](https://user-images.githubusercontent.com/86483834/123447191-93bfb000-d5a7-11eb-9306-628c18994a52.png)
2nd with edit window closed 
![image](https://user-images.githubusercontent.com/86483834/123447442-daada580-d5a7-11eb-8b34-8755b566b19a.png)
3rd image of sorce code for it.
![image](https://user-images.githubusercontent.com/86483834/123447647-17799c80-d5a8-11eb-9bcb-c62d22a14c36.png)

Am I doing something wrong

**Comment by gmmatt** [comment]
Hey fscx.

No, you aren't doing anything wrong. I was able to reproduce this issue. I'll have a look at it. In the meantime, I hope you'll consider joining our Discord channel on the Foundry Discord server. It is also a good place to report issues like this.

**Comment by fscx7** [comment]
Lol at the time I was posting this I was thinking of Cross posting it, but chose not to.  I have a very ambitious goal of getting all of the sourcebook player information and Threats encoded into Foundry.  Once I get my first book done I may try to figure out how to make it a module for gm's to download.

**Comment by gmmatt** [comment]
Hey can you DM me on Discord?

**Comment by gmmatt** [comment]
Wow. That was NOT what I meant to say. Autocorrect. Can you DM me on
discord?
