### ISSUE TITLE
DsN 3D dice not displayed on extra damage dice roll

### ISSUE THREAD

**Issue by parvusdomus** [MetaMorphic-Digital/torgeternity#75]
When you roll an attack the DsN 3d dice are  properly displayed but when you roll the extra damage dice (be it from the character sheet or the chat message) the 3d dice are not shown.

It's probably the way to do this second roll that is not done directly to the chat, in this case you might need to add the call to DsN to be shown with the roll result.

**Comment by gmmatt** [comment]
This is fixed in v. 1.1.2
