### ISSUE TITLE
Create vehicles as actors

### ISSUE THREAD

**Issue by EinKekskruemel** [MetaMorphic-Digital/torgeternity#80]
If you wold be able to create vehicles as actors instead of items you could e.g. drop them to the map, involve them in combats and add weapon-turrets to them.

**Comment by gmmatt** [comment]
Thank you for the suggested feature. I agree that this is the better way to set up vehicles, and it does appear to be the standard used by most other systems. We will definitely consider this for a future addition to the system.

**Comment by pemerson71** [comment]
Matt, isn't this one completed?

**Comment by Algor0113** [comment]
Done so, closed :)
