### ISSUE TITLE
Easy options for Interaction attacks

### ISSUE THREAD

**Issue by SEforbinproject** [MetaMorphic-Digital/torgeternity#81]
Enhancement request

It would be great to have some easy options for quick access to the four interaction attacks for storm knights - even when they don't have adds in the skill.

My players make extensive use of interaction attacks, but all prefer to have their character sheets with the compact skills layout (i.e. skills with no adds not showing). So they frequently have to expand to full skills, hunt through the alphabetical list and locate the relevant interaction attack. A quicker, one-click way of rolling an interaction attack would improve & speed up gameplay.

What would be great would be somehtign along the lines of "always show interaction attacks" as an option for the character sheet, or 4 macros that players could use to roll interaction attacks or the ability to drag skill rolls direct on to the macro bar - something along those lines.

cheers

**Comment by gmmatt** [comment]
Fixed in December updates
