### ISSUE TITLE
Powers: DN is no longer taken from the power-Item

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#82]
Hi there,
it would be nice if in a chat-output the DN of a power (wonder, spell, psionic power) would be displayed in the chat too :)

Thanks for your attention.

**Comment by pemerson71** [comment]
Does the system presently check to see if that number is met?  Players are not always good at math and comparison, especially these days, so having those checks is a good idea.  Perhaps even having those checks when the Player is finished making their Character, then perhaps showing that base Difficulty number would be unnecessary, at least for Characters, yes?

**Comment by Algor0113** [comment]
There's a bug now where the DN is no longer derived from the Power-Item. Don't know why this doesn't work anymore. Needs investigation

**Comment by Algor0113** [comment]
On my side, it's working when Foundry is configured into german. If it's on english, it doesn't. Interesting...
