### ISSUE TITLE
Style bleed issues.

### ISSUE THREAD

**Issue by zeel01** [MetaMorphic-Digital/torgeternity#84]
There are a number of styles which bleed over into module applications causing unexpected formatting and layout quirks.

Related: https://github.com/zeel01/monarch/issues/2

I will further investigate to see which issues are more reasonable to address on the module side, and which issues this system may want to correct.

**Comment by gmmatt** [comment]
Hey Zeel - is this still an issue we need to keep open?

**Comment by Algor0113** [comment]
Never heard of again, may be solved now with monarch?
