### ISSUE TITLE
Card-display mouseover in chat is out of bounds

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#86]
If you mouseover a posted card in the chat, that hasn't got entries yet, the mouseover is out of bounds due to displaying it allways on top of the chatmessage. 
As this will occur more seldom, I don't think this has a high priority :
![Screenshot1](https://user-images.githubusercontent.com/80172941/147413070-49447cd7-94b8-484a-be14-63528f685318.png)

![Screenshot2](https://user-images.githubusercontent.com/80172941/147413150-c2cf3576-ee10-4c42-affe-4ad1002a4f44.png)

**Comment by Algor0113** [comment]
Sorry, 2nd Screenshot is a miss ^^
![Screenshot2](https://user-images.githubusercontent.com/80172941/147413111-c89ff7fe-b7d4-4767-8e79-f0a9e87962bc.png)
'

**Comment by gmmatt** [comment]
Fixed this and another related issue in 2.3.4
