### ISSUE TITLE
Enhanced rolls allways on

### ISSUE THREAD

**Issue by Algor0113** [MetaMorphic-Digital/torgeternity#88]
Hi Matt :)

It would be nice for having a checkbox in System Configuration for having allways the enhanced rolls on (without holding shift). 

Background: My players allways forget to hold shift, as I only want the enhanced rolls. So I thought it could be a enhancement for having a checkbox.

Thank you for your attention, happy new year :)

Regards

**Comment by pemerson71** [comment]
See, I'm mean... I have told my Friends over several game sessions to use Shift, which I feel is a perfectly reasonable thing for them to remember on their own.  I have PTSD that affects my memory very badly and I still remember at least 75% of the time.  If they can't remember, they will when their Character has been beat up a few times. :)

**Comment by Algor0113** [comment]
Enhanced rolls now are always on, implemented, issue therefore closed.
