### ISSUE TITLE
Threat Description Box

### ISSUE THREAD

**Issue by pemerson71** [MetaMorphic-Digital/torgeternity#9]
Would it be possible to have the top of the Threat Description Box, to the right of the Character Stats box, even with the top of that box.

Also, could the input portion above both of those boxes be moved below them, please?  Every time I return to the Stats Tab, even though I'm done using that input portion, it's always open, again.

Thank you.

**Comment by gmmatt** [comment]
The toggle issue is fixed.

**Comment by pemerson71** [comment]
Rock on!!!  Thank you, so much.

**Comment by pemerson71** [comment]
Sorry, closed this entirely by accident.  Was watching my nephew play on switch as I was pushing the comment button.  My apologies.
