### ISSUE TITLE
Adjusting Path Parameter

### ISSUE THREAD

**Issue by Durak-Git** [MetaMorphic-Digital/torgeternity#91]
This part of code prevents an existing macro (same name & command) to be duplicated.
m.command is not the right path, Should be replaced by "m.data.command".
https://github.com/gmmatt/torgeternity/blob/2a0a3e5cdaf80daad771f954d474f339eb1b5328/torgeternity.js#L343

**Comment by gmmatt** [comment]
Macros seem to be working again in 2.3.3
